hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: myfallbackcmd
                fallbackUri: forward:/hystrix/fallback
        - id: file_route
          uri: lb://file-service
          #          uri: http://localhost:8081
          predicates:
            - Path=/file-service/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: myfallbackcmd
                fallbackUri: forward:/hystrix/fallback
server:
  port: 4000

