spring:
  boot:
    admin:
      client:
        url: http://localhost:5000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: file
  redis:
    host: localhost
    port: 6379
    database: 0
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS